2025-09-27 16:48:45,526 - error_handler - ERROR - AskPdf Error: {'timestamp': '2025-09-27T16:48:45.526794', 'error_code': 'INVALID_FILE_FORMAT', 'message': "File type .txt not allowed. Allowed types: ['.pdf']", 'details': {'filename': 'test.txt', 'extension': '.txt'}}
2025-09-27 16:48:45,527 - error_handler - ERROR - AskPdf Error: {'timestamp': '2025-09-27T16:48:45.527802', 'error_code': 'FILE_SIZE_EXCEEDED', 'message': 'File size 100.00MB exceeds maximum allowed size of 50MB', 'details': {'file_size_mb': 100.0, 'max_size_mb': 50}}
2025-09-27 16:48:45,528 - error_handler - ERROR - AskPdf Error: {'timestamp': '2025-09-27T16:48:45.527802', 'error_code': 'FILE_NOT_FOUND', 'message': 'Test file error', 'details': {'file': 'test.pdf'}}
2025-09-27 16:50:09,128 - error_handler - ERROR - AskPdf Error: {'timestamp': '2025-09-27T16:50:09.128264', 'error_code': 'INVALID_FILE_FORMAT', 'message': "File type .txt not allowed. Allowed types: ['.pdf']", 'details': {'filename': 'test.txt', 'extension': '.txt'}}
2025-09-27 16:50:09,130 - error_handler - ERROR - AskPdf Error: {'timestamp': '2025-09-27T16:50:09.130400', 'error_code': 'FILE_SIZE_EXCEEDED', 'message': 'File size 100.00MB exceeds maximum allowed size of 50MB', 'details': {'file_size_mb': 100.0, 'max_size_mb': 50}}
2025-09-27 16:50:09,131 - error_handler - ERROR - AskPdf Error: {'timestamp': '2025-09-27T16:50:09.131654', 'error_code': 'FILE_NOT_FOUND', 'message': 'Test file error', 'details': {'file': 'test.pdf'}}
2025-09-27 16:51:08,783 - error_handler - ERROR - AskPdf Error: {'timestamp': '2025-09-27T16:51:08.783381', 'error_code': 'INVALID_FILE_FORMAT', 'message': "File type .txt not allowed. Allowed types: ['.pdf']", 'details': {'filename': 'test.txt', 'extension': '.txt'}}
2025-09-27 16:51:08,784 - error_handler - ERROR - AskPdf Error: {'timestamp': '2025-09-27T16:51:08.783381', 'error_code': 'FILE_SIZE_EXCEEDED', 'message': 'File size 100.00MB exceeds maximum allowed size of 50MB', 'details': {'file_size_mb': 100.0, 'max_size_mb': 50}}
2025-09-27 16:51:08,784 - error_handler - ERROR - AskPdf Error: {'timestamp': '2025-09-27T16:51:08.784652', 'error_code': 'FILE_NOT_FOUND', 'message': 'Test file error', 'details': {'file': 'test.pdf'}}
2025-09-27 16:52:00,655 - error_handler - ERROR - AskPdf Error: {'timestamp': '2025-09-27T16:52:00.655130', 'error_code': 'INVALID_FILE_FORMAT', 'message': "File type .txt not allowed. Allowed types: ['.pdf']", 'details': {'filename': 'test.txt', 'extension': '.txt'}}
2025-09-27 16:52:00,656 - error_handler - ERROR - AskPdf Error: {'timestamp': '2025-09-27T16:52:00.656137', 'error_code': 'FILE_SIZE_EXCEEDED', 'message': 'File size 100.00MB exceeds maximum allowed size of 50MB', 'details': {'file_size_mb': 100.0, 'max_size_mb': 50}}
2025-09-27 16:52:00,657 - error_handler - ERROR - AskPdf Error: {'timestamp': '2025-09-27T16:52:00.657268', 'error_code': 'FILE_NOT_FOUND', 'message': 'Test file error', 'details': {'file': 'test.pdf'}}
2025-09-27 16:52:00,931 - config - WARNING - HUGGINGFACEHUB_API_TOKEN is not set - embeddings may not work properly
2025-09-27 16:52:00,931 - config - WARNING - HUGGINGFACEHUB_API_TOKEN is not set - embeddings may not work properly
2025-09-27 17:13:19,999 - chromadb.telemetry.product.posthog - INFO - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
2025-09-27 17:14:00,442 - error_handler - ERROR - AskPdf Error: {'timestamp': '2025-09-27T17:14:00.442211', 'error_code': 'DB_OPERATION_ERROR', 'message': "Unexpected error while listing documents: object dict can't be used in 'await' expression", 'details': {}, 'original_error': "object dict can't be used in 'await' expression", 'traceback': 'Traceback (most recent call last):\n  File "C:\\Users\\paras\\Desktop\\New folder\\main.py", line 159, in list_docs\n    all_docs = await vectordb.get()\n               ^^^^^^^^^^^^^^^^^^^^\nTypeError: object dict can\'t be used in \'await\' expression\n'}
2025-09-27 17:14:09,813 - error_handler - ERROR - AskPdf Error: {'timestamp': '2025-09-27T17:14:09.813012', 'error_code': 'DB_OPERATION_ERROR', 'message': "Unexpected error while listing documents: object dict can't be used in 'await' expression", 'details': {}, 'original_error': "object dict can't be used in 'await' expression", 'traceback': 'Traceback (most recent call last):\n  File "C:\\Users\\paras\\Desktop\\New folder\\main.py", line 159, in list_docs\n    all_docs = await vectordb.get()\n               ^^^^^^^^^^^^^^^^^^^^\nTypeError: object dict can\'t be used in \'await\' expression\n'}
2025-09-27 17:15:40,078 - chromadb.telemetry.product.posthog - INFO - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
2025-09-27 17:16:45,433 - error_handler - ERROR - AskPdf Error: {'timestamp': '2025-09-27T17:16:45.433394', 'error_code': 'DB_OPERATION_ERROR', 'message': "Unexpected error during document deletion: object dict can't be used in 'await' expression", 'details': {'requested_ids': ['9bf0d8d7-33bf-4801-83cb-038c24c02f55']}, 'original_error': "object dict can't be used in 'await' expression", 'traceback': 'Traceback (most recent call last):\n  File "C:\\Users\\paras\\Desktop\\New folder\\main.py", line 202, in delete_docs\n    existing_docs = await vectordb.get()\n                    ^^^^^^^^^^^^^^^^^^^^\nTypeError: object dict can\'t be used in \'await\' expression\n'}
2025-09-27 17:17:48,703 - chromadb.telemetry.product.posthog - INFO - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
2025-09-27 17:18:32,647 - error_handler - ERROR - AskPdf Error: {'timestamp': '2025-09-27T17:18:32.647163', 'error_code': 'DB_OPERATION_ERROR', 'message': "Unexpected error during bulk deletion: object dict can't be used in 'await' expression", 'details': {}, 'original_error': "object dict can't be used in 'await' expression", 'traceback': 'Traceback (most recent call last):\n  File "C:\\Users\\paras\\Desktop\\New folder\\main.py", line 241, in delete_all_docs\n    all_docs = await vectordb.get()\n               ^^^^^^^^^^^^^^^^^^^^\nTypeError: object dict can\'t be used in \'await\' expression\n'}
2025-09-27 17:19:44,542 - chromadb.telemetry.product.posthog - INFO - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
2025-09-27 17:21:45,629 - chromadb.telemetry.product.posthog - INFO - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
